### ISSUE TITLE
Could you make a new release to pick up regex-syntax 0.6?

### ISSUE THREAD

**Issue by adamfaulkner-at** [tantivy-search/fst#17]
Hi,

I noticed that regex-syntax has been updated to version 0.6 about 2 years ago, but since there hasn't been a release in a while, the latest version still uses version 0.4. 

It would be nice to be able to limit the number of different versions of dependencies that are being used in my project. All of my other dependencies rely on version 0.6 of regex-syntax.

Could you make a new release of tantivy-fst to avoid this?

**Comment by fulmicoton** [comment]
@PSeitz can you have a look?

**Comment by jonassmedegaard** [comment]
seems this bugreport can be closed: v0.4.0 was released 2022-09-28.
