### ISSUE TITLE
Stream terms backward

### ISSUE THREAD

**Issue by fulmicoton** [tantivy-search/fst#3]
Make it possible to stream terms backward.

**Comment by halvorboe** [comment]
Seems doable. 

Current plan:
- [ ] Modifying the underlying StreamWithState iterator to support allow for a `.seek(min/max)` and making the next function iterate the other way through the trie. This means adding min/max to the state of the stream. 
- [ ] Exposing it to the external API. Initial thought is adding a `.reverse()` to the Stream. This would include doing the seek (min/max) lazily. 

Is this a good starting point?

**Comment by fulmicoton** [comment]
This does not sound crazy for sure.

Maybe I would not have `.seek(min/max)`, have a `.reverse()` in the stream builder and either return a different flag, or have a bool (or a generic!?) in the stream to mark whether it goes forward or backward.

**Comment by halvorboe** [comment]
#4 

Experimented a bit with how to implement it. Not 100% sure that this is the right way to go, is increasing the complexity of an already very complex function.

**Comment by fulmicoton** [comment]
I think this is looking good. Can you add a unit tests so that we have something we can iterate on more safely?

So as you have spotted, the only difference between iterating backward or forward is in whether we iterate transition forward or backward... And when we emit the current node.

Maybe we could externalize the iteration of transitions to a Trait and put that as a generics of the StreamWithState. If it does not add much complexity that could be a nice way to deal with this problem.

**Comment by halvorboe** [comment]
Have made it so all the unit tests for forward iteration go the other way as well. They are just commented out so I can make sure I'm not breaking forward iteration while refactoring. Will look into making the macro generate 2 tests - one for forwards and one for backwards.

Will look into making it work with generics.
